---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(sae, exclude = "select")
library(tidycensus)
library(tidyverse)

census_api_key("9fb9cc8584a00b7006e7550c685129b65240b9aa")
```

```{r echo=FALSE}
#lookup <- load_variables(2019, "acs5", cache = TRUE)
```



```{r echo=FALSE}
selected_states = c("MN",  "ND", "SD" )  #"WI", "IA",
## Population counts
pop <- get_acs(geography = "county", 
        variables = "B01003_001", 
        year = 2019,
        state = selected_states)

## Poverty counts
pov <- get_acs(geography = "county", 
        variables = "B17001_002",
        year = 2019,
        state = selected_states)


poverty <- data.frame(county=pop$NAME, pop=pop$estimate, pov=pov$estimate, SE=pov$moe/1.645) %>%
   mutate(povPerc=pov/pop, povPercSE=SE/pop)
poverty %>% head()
```


```{r message=FALSE}
race = get_acs(geography = "county", 
              variables = c(total="B02001_001", white="B02001_002", 
                            black="B02001_003", native="B02001_004", 
                            asian="B02001_005", 
                            other1="B02001_006", other2="B02001_007", 
                            mult1="B02001_008", mult2="B02001_009", 
                            mult3="B02001_010"), 
              state = selected_states, 
              year = 2019)

race = race %>% 
  select(NAME, variable, estimate) %>% 
  spread(key=variable, value=estimate ) %>% 
  mutate(other=other1+other2+mult1+mult2+mult3) %>% 
  select(-other1, -other2, -mult1, -mult2, -mult3) %>% 
  relocate(NAME, total, white, native, black, asian, other) %>% 
  mutate(white=white/total, native=native/total, black=black/total, 
         asian=asian/total, other=other/total)
race = race %>% select (NAME, white, native, black, asian, other)
race %>% head()
```



```{r message=FALSE}
latino = get_acs(geography = "county", 
              variables = c(non_hispanic="B08134_001", hispanic="B08134_010"), 
              state = selected_states, 
              year = 2019)

latino = latino %>% 
  select(NAME, variable, estimate) %>% 
  spread(key=variable, value=estimate ) %>% 
  mutate(total = non_hispanic+hispanic) %>% 
  mutate(non_hispanic=non_hispanic/total, hispanic= hispanic/total) %>% 
  select(-total)
latino %>% head()
```


```{r}
parents = get_acs(geography = "county", 
              variables = c(married = "B09002_002", 
                            male_only = "B09002_009", 
                            female_only = "B09002_015"), 
              state = selected_states, 
              year = 2019)
parents = parents %>% 
  select(NAME, variable, estimate) %>% 
  spread(key=variable, value=estimate ) %>% 
  mutate(total=female_only + male_only + married) %>% 
  mutate(married=married/total, male_only = male_only/total, female_only=female_only/total) %>% 
  select(-total)
parents %>% head()
```



```{r message=FALSE}
vehicle = get_acs(geography = "county",
              variables = c(no_car = "B08014_002", total = "B08014_001"),
              state = selected_states,
              year = 2019)

vehicle = vehicle %>%
  select(NAME, variable, estimate) %>%
  spread(key=variable, value=estimate ) %>%
  mutate(no_car=no_car/total) %>%
  select(-total)
vehicle %>% head()
```




```{r message=FALSE}
X = race %>% left_join(latino) %>% left_join(parents) %>% 
  left_join(vehicle) %>%
  relocate(county=NAME)  
X
```


```{r message=FALSE}
all_data = poverty %>% left_join(X) %>% select(-white, -non_hispanic, -married, -other)
all_data %>% head()
```




```{r}
N = all_data %>% nrow()

gls = lm(povPerc~ native + black + asian  + hispanic + 
          female_only + male_only + no_car , #white +long_commute, #+ other
         data=all_data, weights = 1/(all_data$povPercSE^2))
gls %>% summary()
```



```{r}
xi = all_data[, 7:ncol(all_data)] %>% as.matrix()
resultFH <- eblupFH(all_data$povPerc ~ xi, all_data$povPercSE^2, method="FH")
resultFH$fit$goodness

resultFH$fit$estcoef
```


```{r}
data.frame(GLS = gls$fitted.values, y=all_data$povPerc, EB_FH=resultFH$eblup) %>% 
  gather(key="model", value="estimate", -y) %>% 
  ggplot(aes(x=log(y), y=log(estimate), color=model),  alpha=0.5) + geom_point() + 
  geom_abline(slope = 1, lty=2, alpha=0.5) + theme_bw()
```

```{r}
data.frame(gls = gls$fitted.values, y=all_data$povPerc, pop=all_data$pop,
           se = all_data$povPercSE, fh=resultFH$eblup) %>% 
        gather(key="model", value="estimate", -se, -y, -pop) %>% 
  ggplot(aes(x=log(pop), y=y/estimate, color=model)) + geom_point() + 
  geom_hline(yintercept = 1, alpha=0.5, lty=2) + theme_bw()

```






```{r}
data.frame(gls = gls$fitted.values, y=all_data$povPerc, 
           se = all_data$povPercSE, fh=resultFH$eblup) %>% 
        gather(key="model", value="estimate", -se, -y) %>% 
  #filter(model=="fh") %>% 
  ggplot(aes(x=se, y=y/estimate, color=model)) + geom_point() + 
  geom_hline(yintercept = 1, alpha=0.5, lty=2) + theme_bw()

```

```{r}
data.frame(gls = gls$fitted.values, y=all_data$povPerc, 
           se = all_data$povPercSE, fh=resultFH$eblup) %>% 
        gather(key="model", value="estimate", -se, -y) %>% 
  filter(model=="fh") %>% 
  ggplot(aes(x=se, y=y/estimate, color=model)) + geom_point() + 
  geom_hline(yintercept = 1, alpha=0.5, lty=2) + theme_bw()

```





